version: '3.6'
services:
  db:
    container_name: tm_db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    container_name: tm_api
    build: ./todolist
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./todolist:/api
  app:
    container_name: tm_app
    build: ./time-manager
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./time-manager:/app
volumes:
  pgdata:
