version: '3.6'
services:
  db:
    container_name: tm_db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todolist_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  api:
    container_name: tm_api
    build: ./todolist
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - ./todolist:/app
volumes:
  pgdata:
