version: '3.6'
services:
  api:
    build:
      target: app_test
      context: ./todolist
      args:
        - MIX_ENV=test
    environment:
      MIX_ENV: test
    env_file:
      - .env
    volumes:
      - ./todolist:/api
