- name: Deploy back
  docker_container:
    name: back
    image: matska/poo_api:latest
    ports:
      - '{{ EXPOSED_API_PORT }}:{{ API_PORT }}'
      - '{{ EXPOSED_API_SSL_PORT }}:443'
    env:
      SECRET_KEY_BASE: 3rDcAYtHHrqfuOuKGH1pMezLbbTIiAuAHEzG3ULrYPWfYs11wvOmAmRTk/jVyoQh
      API_PORT: '{{ API_PORT }}'
      # DATABASE_URL: 'postgres://{{ db_user }}:{{ db_password }}@{{ db_host }}:{{ db_port }}/{{ db_name }}'
      DATABASE_URL: postgres://postgres:postgres@172.17.0.2:5432/postgres

- name: Run command DB migration
  shell: "docker exec -it back ./bin/migrate"

- name: Run command DB seed
  docker_container:
    name: back_seed
    image: matska/poo_api_seed:latest
    env:
      SECRET_KEY_BASE: 3rDcAYtHHrqfuOuKGH1pMezLbbTIiAuAHEzG3ULrYPWfYs11wvOmAmRTk/jVyoQh
      API_PORT: '{{ API_PORT }}'
      DATABASE_URL: postgres://postgres:postgres@172.17.0.2:5432/postgres
