name: Deploy Release

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build back image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./todolist
          target: app_prod
          build-args: MIX_ENV=prod
          push: true
          tags: matska/poo_api:latest

      - name: Build front image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./time-manager
          target: app_prod
          build-args: MIX_ENV=prod
          push: true
          tags: matska/poo_app:latest

  deploy_with_ansible:
    name: Deploy with ansible
    runs-on: ubuntu-latest
    # needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install ansible
        run: |
          sudo apt -yqq update
          sudo apt -yqq install ansible

      - name: Setup SSH
        run: |
          cd ansible
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          touch ~/.ssh/config
          chmod 600 ~/.ssh/config
          chmod 600 ./id_rsa
          eval `ssh-agent -s`
          ssh-add ./id_rsa
          echo "Host 51.75.204.29" >> ~/.ssh/config
          echo "  HostName 51.75.204.29" >> ~/.ssh/config
          echo "  User debian" >> ~/.ssh/config
          echo "  Port 30000" >> ~/.ssh/config
      
      - name: Ping remote nodes
        run: |
          cd ansible
          sudo ansible machines -m ping -i inventory.yaml -vvv --ssh-extra-args="-o StrictHostKeyChecking=no"

      - name: Run deploy playbook
        run: |
          cd ansible
          sudo ansible-playbook -i inventory.yaml deploy.yml -vv --extra-vars "ansible_sudo_pass=debian" --ssh-extra-args="-o StrictHostKeyChecking=no"
