name: builds
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "2.12.2"

      - name: Run tests
        run: make test

  run_dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "2.12.2"

      - name: Run project as dev
        run: make dev

      - name: Stop project
        run: make stop

  run_prod:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: "2.12.2"

      - name: Run project as prod
        run: make prod

      - name: Stop project
        run: make stop
