name: builds
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'

      - name: Install project
        run: make install

      - name: Run tests
        run: make test
